# -*- mode: ruby -*-
# vi: set ft=ruby :
# Dotenvから変数をロード
#Dotenv.load

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
# 実行するShellScript

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	Encoding.default_external = 'UTF-8'
  config.vm.box = "CentOS6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
  config.vm.define :web do |web|
    web.vm.network :forwarded_port, guest: 80, host: 1234
    web.vm.network :private_network, ip: "192.168.33.10"
    web.vm.synced_folder "../", "/share",
      owner: "vagrant", group: "vagrant", create: true

    web.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.name = "CentOS-laravel-project"
    end
    web.vm.provision "shell", :path => "provision/bootstrap.sh"

  end
end
